In [1]:
pip install nltk


Note: you may need to restart the kernel to use updated packages.Collecting nltk
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
     ---------------------------------------- 0.0/42.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/42.0 kB ? eta -:--:--
     --------- ------------------------------ 10.2/42.0 kB ? eta -:--:--
     --------------------------- ---------- 30.7/42.0 kB 330.3 kB/s eta 0:00:01
     -------------------------------------  41.0/42.0 kB 393.8 kB/s eta 0:00:01
     -------------------------------------- 42.0/42.0 kB 291.1 kB/s eta 0:00:00
     ---------------------------------------- 0.0/57.6 kB ? eta -:--:--
     ----------------------------------- ---- 51.2/57.6 kB 2.6 MB/s eta 0:00:01
     ---------------------------------------- 57.6/57.6 kB 1.0 MB/s eta 0:00:00
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ----------------------- ---------


[notice] A new release of pip is available: 24.0 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\JY\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\JY\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\JY\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [1]:
pip install pandas

  Using cached pandas-2.2.2-cp312-cp312-win_amd64.whl.metadata (19 kB)
  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached pandas-2.2.2-cp312-cp312-win_amd64.whl (11.5 MB)
Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
pip install scikit-learn


     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ------------------- ------------------ 30.7/60.8 kB 640.0 kB/s eta 0:00:01
     ---------------------------------------- 60.8/60.8 kB 1.1 MB/s eta 0:00:00
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
   ---------------------------------------- 0.0/10.9 MB ? eta -:--:--
    --------------------------------------- 0.2/10.9 MB 3.9 MB/s eta 0:00:03
   - -------------------------------------- 0.4/10.9 MB 3.9 MB/s eta 0:00:03
   - -------------------------------------- 0.5/10.9 MB 3.9 MB/s eta 0:00:03
   -- ------------------------------------- 0.6/10.9 MB 3.3 MB/s eta 0:00:04
   -- ------------------------------------- 0.7/10.9 MB 2.8 MB/s eta 0:00:04
   -- ------------------------------------- 0.7/10.9 MB 2.7 MB/s eta 0:00:04
   -- ------------------------------------- 0.8/10.9 MB 2.4 MB/s eta 0:00:05
   -- ------------------------------------- 0.8/10.9 MB 2.4 MB/s eta 0:00:05
   --- ------


[notice] A new release of pip is available: 24.0 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
#NLP IDF AFTER APPLYING MACHINE LEARNING ALGORITHM 

#IMPORTING FOR IDF(NLP AND ML ALGORITHM)
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem  import WordNetLemmatizer
import string
import pandas as pd 
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,classification_report
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
stop_words = set(stopwords.words('english'))
#CLEANING FUNCTION COMMOM CODE FOR ALL DATASET CLEANING
def clean_text(texts):
    clean_texts = []
    for text in texts:
        text=text.lower()
        tokens = word_tokenize(text) #change its like list
        cleaned_tokens=[]
        lemmatizer = WordNetLemmatizer()
        for word in tokens:
            if (word.isalnum()) and (not word .isdigit()) and (word not in stop_words):
                word = word.strip(string.punctuation) #remove space,punctu
                word = lemmatizer.lemmatize(word)  #change plural to singular
                word = word.strip()  #deleted extra spaces
                cleaned_tokens.append(word)
            cleaned_text = " ".join(cleaned_tokens)
        clean_texts.append(cleaned_text)
    return clean_texts
#DATASET READING FITTING MODELS FOR NLP PERFORMING IDF
df = pd.read_csv(r"D:\Final project\Toxic Tweet\FinalBalancedDataset.csv\FinalBalancedDataset.csv")
df = df.sample(2000)
corpus = clean_text(df['tweet'].values)
model=TfidfVectorizer()
data = pd.DataFrame(model.fit_transform(corpus).toarray())
data.columns = model.get_feature_names_out()
data.index= corpus
le = LabelEncoder()
df['tweet'] = le.fit_transform(df['tweet'])
data['tweet'] = df['tweet']
X=data.drop(['tweet'],axis=1)
y=df['tweet']
#DEFINING MODELS FOR ML AND FITTING ,TEST AND TRAIN 
x_train,x_test,y_train,y_test =train_test_split(X,y,test_size=0.2)
models = (LogisticRegression(),KNeighborsClassifier(),SVC(),DecisionTreeClassifier(),RandomForestClassifier(),AdaBoostClassifier(),GradientBoostingClassifier())
for model in models:
    model.fit(x_train,y_train)
    train_pred = model.predict(x_train)
    test_pred = model.predict(x_test)
    #EVALUATION

    print(f"********(type(model).__name__)********")
    print(f"Train Accuracy: {accuracy_score(y_train,train_pred)}")
    print(f"Train Precision: {precision_score(y_train,train_pred,average="micro")}")
    print(f"Train Recall:{recall_score(y_train,train_pred,average="micro")}")
    print(f"Train F1 Score:{f1_score(y_train,train_pred,average="micro")}")

    print(f"Test Accuracy: {accuracy_score(y_test,test_pred)}")
    print(f"Test Precision: {precision_score(y_test,test_pred,average="micro")}")
    print(f"Test Recall:{recall_score(y_test,test_pred,average="micro")}")
    print(f"Test F1 Score:{f1_score(y_test,test_pred,average="micro")}")

#compare test precision and find which algo is best




********(type(model).__name__)********
Train Accuracy: 0.019375
Train Precision: 0.019375
Train Recall:0.019375
Train F1 Score:0.019375
Test Accuracy: 0.01
Test Precision: 0.01
Test Recall:0.01
Test F1 Score:0.01
********(type(model).__name__)********
Train Accuracy: 0.151875
Train Precision: 0.151875
Train Recall:0.151875
Train F1 Score:0.151875
Test Accuracy: 0.01
Test Precision: 0.01
Test Recall:0.01
Test F1 Score:0.01
********(type(model).__name__)********
Train Accuracy: 0.99
Train Precision: 0.99
Train Recall:0.99
Train F1 Score:0.99
Test Accuracy: 0.01
Test Precision: 0.01
Test Recall:0.01
Test F1 Score:0.01
********(type(model).__name__)********
Train Accuracy: 0.995625
Train Precision: 0.995625
Train Recall:0.995625
Train F1 Score:0.995625
Test Accuracy: 0.0125
Test Precision: 0.0125
Test Recall:0.0125
Test F1 Score:0.0125
********(type(model).__name__)********
Train Accuracy: 0.995625
Train Precision: 0.995625
Train Recall:0.995625
Train F1 Score:0.995625
Test Accuracy: 0.012

d:\Final project\.venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


********(type(model).__name__)********
Train Accuracy: 0.02
Train Precision: 0.02
Train Recall:0.02
Train F1 Score:0.02
Test Accuracy: 0.01
Test Precision: 0.01
Test Recall:0.01
Test F1 Score:0.01


KeyboardInterrupt: 

In [22]:
from sklearn.metrics import confusion_matrix, roc_auc_score
 # Confusion Matrix
cm = confusion_matrix(y_test, test_pred)
print(f"Confusion Matrix:\n{cm}")
    
if cm.shape == (2, 2):
     tn, fp, fn, tp = cm.ravel()
     print(f"Confusion Matrix: TN={tn}, FP={fp}, FN={fn}, TP={tp}")


Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
